In [1]:
#Question1
import numpy as np
array = np.array([1,3,4,7,9])
print(array.tolist())

[1, 3, 4, 7, 9]


In [3]:
#Questuion2 
import numpy as np
a = np.array([[1,2,3],[4,7,5],[9,3,8]])
print(a)
b = np.trace(a)
print(b)

[[1 2 3]
 [4 7 5]
 [9 3 8]]
16


In [9]:
#Questuion3
import numpy as np
a = np.array([[1,2,4,6],[4,7,3,5]])
b = []
X = 3
for i in np.nditer(a):
    if i > X:
        b.append(i)
c = np.array(b)
print(c)

[4 6 4 7 5]


In [6]:
#Question4
import numpy as np
A = np.array([[5,9,2],[2,4,7]])
B = np.array([[1,4,7],[9,3,5]])
C = np.add(A,B)
print(C)

[[ 6 13  9]
 [11  7 12]]


In [9]:
#Question5
import numpy as np
a = np.array([[1,3,5],[7,9,2],[5,6,4]])
print(a)
a1 = np.mean(a[0,:])
print(a1)
a2 = np.mean(a[1,:])
print(a2)
a3 = np.mean(a[2,:])
print(a3)
b = a1 - a2 - a3
print(b)


[[1 3 5]
 [7 9 2]
 [5 6 4]]
3.0
6.0
5.0
-8.0
